dependencies:
- condition: kiali.enabled
  name: kiali
  repository: file://./charts/kiali
  version: 2.1.0
- condition: tracing.enabled
  name: tracing
  repository: file://./charts/tracing
  version: 1.63.0
