apiVersion: apps/v1
kind: Deployment
metadata:
  name: sr-bundle-app-frontend-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      sr-app: app-frontend
  template:
    metadata:
      labels:
        sr-app: app-frontend
    spec:
      {{- if .Values.privateRegistry.registrySecret }}
      imagePullSecrets:
      - name: {{ .Values.privateRegistry.registrySecret }}
      {{- end }}
      containers:
      - name: app-frontend
        image: {{ template "registry_url" . }}{{ .Values.image.appFrontend.repository }}:{{ .Values.image.appFrontend.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "100m"
            ephemeral-storage: "10Gi"
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: sr-bundle-app-frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    sr-app: app-frontend
