apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rancher-supportability-review.fullname" . }}-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rancher-supportability-review.fullname" . }}-cr
subjects:
- kind: ServiceAccount
  name: {{ include "rancher-supportability-review.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
