apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rancher.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  collectorImageRepository: {{ template "registry_url" . }}{{ .Values.image.collector.repository }}:{{ .Values.image.collector.tag }}
  analyzerImageRepository: {{ template "registry_url" . }}{{ .Values.image.analyzer.repository }}:{{ .Values.image.analyzer.tag }}
  collectorRequestsCPU: {{ .Values.resources.collector.requests.cpu }}
  collectorRequestsMemory: {{ .Values.resources.collector.requests.memory }}
  collectorLimitsCPU: {{ .Values.resources.collector.limits.cpu }}
  collectorLimitsMemory: {{ .Values.resources.collector.limits.memory }}
  analyzerRequestsCPU: {{ .Values.resources.analyzer.requests.cpu }}
  analyzerRequestsMemory: {{ .Values.resources.analyzer.requests.memory }}
  analyzerLimitsCPU: {{ .Values.resources.analyzer.limits.cpu }}
  analyzerLimitsMemory: {{ .Values.resources.analyzer.limits.memory }}
  {{- if .Values.privateRegistry.registrySecret }}
  imagePullSecretName: {{ .Values.privateRegistry.registrySecret }}
  {{- end }}
---
{{- if .Values.privateRegistry.createSecret }}
{{- if .Values.privateRegistry.registrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.privateRegistry.registrySecret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "secret" . }}
{{- end }}
{{- end }}
