url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.7
commit: c6bf387fb767ac90ea36a1971232a17ff6e55a56
version: 106.1.2
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.7
      commit: c6bf387fb767ac90ea36a1971232a17ff6e55a56
doNotRelease: false
