{{- define "logging-operator.logging.aks" -}}
{{- $individualValues := .Values.additionalLoggingSources.aks -}}
metadata:
  name: {{ .Release.Name }}-aks
spec:
  {{- include "logging-operator.individualLoggingRef" $individualValues | nindent 2 }}
  fluentd:
  {{- include "logging-operator.individualFluentd" $individualValues | nindent 4 }}
{{- end -}}
{{- if .Values.additionalLoggingSources.aks.enabled }}
{{- include "logging-operator.logging" (list . "logging-operator.logging.aks") -}}
{{- end }}
