annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: longhorn-system
  catalog.cattle.io/release-name: longhorn-crd
apiVersion: v1
appVersion: v1.8.2
description: Installs the CRDs for longhorn.
name: longhorn-crd
version: 104.3.1+up1.8.2
