annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Harvester Cloud Provider
  catalog.cattle.io/kube-version: '>= 1.18.0-0 < 1.25.0-0'
  catalog.cattle.io/namespace: kube-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.8.0-0'
  catalog.cattle.io/release-name: harvester-cloud-provider
  catalog.cattle.io/ui-component: harvester-cloud-provider
  catalog.cattle.io/upstream-version: 0.1.13
apiVersion: v2
appVersion: v0.1.4
description: A Helm chart for Harvester Cloud Provider
keywords:
- infrastructure
- harvester
maintainers:
- name: harvester
name: harvester-cloud-provider
type: application
version: 101.0.0+up0.1.13
