dependencies:
- condition: kiali.enabled
  name: kiali
  repository: file://./charts/kiali
  version: 1.89.3
- condition: tracing.enabled
  name: tracing
  repository: file://./charts/tracing
  version: 1.60.0
