image:
  repository: rancher/mirrored-cluster-api-controller
  tag: v1.9.5
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""
  kubectl:
    repository: rancher/kubectl
    tag: v1.32.2
    pullPolicy: IfNotPresent

# tolerations for the capi-controller-manager deployment. See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ for more info
tolerations: []

nodeSelector: {}

## PriorityClassName assigned to deployment.
priorityClassName: ""

extraEnv: []
args:
  - "--diagnostics-address=localhost:8443"
  - "--feature-gates=MachinePool=false,ClusterResourceSet=false,ClusterTopology=false,RuntimeSDK=false"
