{{- define "logging-operator.fluentbitagent.k3s-openrc" -}}
{{- $logPath := "/var/log/k3s.log" -}}
{{- $individualValues := .Values.additionalLoggingSources.k3s.fluentbit -}}
metadata:
  name: {{ .Release.Name }}-k3s
spec:
  {{- include "logging-operator.individualFluentbitLoggingRef" $individualValues | nindent 2 }}
  disableKubernetesFilter: true
  extraVolumeMounts:
    - source: {{ $logPath }}
      destination: {{ $logPath }}
      readOnly: true
  inputTail:
    Tag: "k3s"
    Path: {{ $logPath }}
    Path_Key: filename
  {{- include "logging-operator.individualFluentbit" $individualValues | nindent 2 }}
{{- end -}}
{{- if and .Values.additionalLoggingSources.k3s.enabled (eq .Values.additionalLoggingSources.k3s.container_engine "openrc")}}
{{- include "logging-operator.fluentbitagent" (list . "logging-operator.fluentbitagent.k3s-openrc") -}}
{{- end }}
