url: https://github.com/rancher/backup-restore-operator/releases/download/v5.0.4-rc.1/rancher-backup-5.0.4-rc.1.tgz
version: 104.1.0
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/backup-restore-operator/releases/download/v5.0.4-rc.1/rancher-backup-crd-5.0.4-rc.1.tgz
