url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/69.8.2-rancher.5
commit: 31ed8fa3fc711123ee61b269273cae039ae5edb5
version: 106.1.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/69.8.2-rancher.5
      commit: 31ed8fa3fc711123ee61b269273cae039ae5edb5
doNotRelease: false
