url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/66.7.1-rancher.14
commit: d9c8b66a67e954475ef877369d89f4043f1181a3
version: 105.2.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/66.7.1-rancher.14
      commit: d9c8b66a67e954475ef877369d89f4043f1181a3
doNotRelease: false
